% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames*,x11names*}{xcolor}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Ejercicios Tema 4 - Contraste hipótesis. Taller 1},
  pdfauthor={Ricardo Alberich, Juan Gabriel Gomila y Arnau Mir},
  colorlinks=true,
  linkcolor=red,
  filecolor=Maroon,
  citecolor=blue,
  urlcolor=blue,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\renewcommand{\contentsname}{Contenidos}

\title{Ejercicios Tema 4 - Contraste hipótesis. Taller 1}
\author{Ricardo Alberich, Juan Gabriel Gomila y Arnau Mir}
\date{Curso completo de estadística inferencial con R y Python}

\begin{document}
\maketitle

{
\hypersetup{linkcolor=blue}
\setcounter{tocdepth}{2}
\tableofcontents
}
\hypertarget{contraste-hipuxf3tesis-taller-1.}{%
\section{Contraste hipótesis taller
1.}\label{contraste-hipuxf3tesis-taller-1.}}

Los siguientes ejercicios son de puro cálculo. Seguid la teoría y
utilizar R para el cálculo de los estadísticos y de los cuantiles de los
\(p\)-valores.

\hypertarget{ejercicio-1}{%
\subsection{Ejercicio 1}\label{ejercicio-1}}

En muestra aleatoria simple de tamaño \(n=36\) extraída de una población
normal con \(\sigma^2=12^2\) hemos obtenido la siguiente media muestral
\(\overline{x}=62.5\), Contrastar al nivel de significación
\(\alpha=0.05\), la hipótesis nula \(\mu=61\) contra la alternativa
\(\mu<60\). Resolver calculando el \(p\)-valor del contraste.

\hypertarget{soluciuxf3n}{%
\subsubsection{Solución}\label{soluciuxf3n}}

Tenemos que contrastar

\[
\left\{
\begin{array}{ll}
H_{0}:\mu=60\\
H_{1}:\mu<60
\end{array}
\right.
\]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sigma2=}\DecValTok{12}\OperatorTok{^}\DecValTok{2}
\NormalTok{sigma2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 144
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n=}\DecValTok{36}
\NormalTok{n}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 36
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{media_muestral=}\FloatTok{62.5}
\NormalTok{media_muestral}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 62.5
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{alpha=}\FloatTok{0.05}
\NormalTok{alpha}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.05
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mu0=}\DecValTok{60}
\NormalTok{mu0}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 60
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{z0 =}\StringTok{ }\NormalTok{(media_muestral}\OperatorTok{-}\NormalTok{mu0)}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(sigma2}\OperatorTok{/}\NormalTok{n)}
\NormalTok{z0}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.25
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#valor crítico para mu< 60}
\NormalTok{valor_critico=}\StringTok{ }\KeywordTok{qnorm}\NormalTok{(alpha)}
\NormalTok{valor_critico}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -1.644854
\end{verbatim}

Bajo estas condiciones, normalidad muestra aleatoria simple y con los
datos de la muestra el estadístico de contraste es:

\[z_0=\frac{\overline{x}-\mu_0}{\frac{\sigma}{\sqrt{n}}}=
\frac{62.5-60}{\frac{12}{\sqrt{36}}}
=1.25\]

La región de rechazo contra \(H_1:\mu <60\) es rechazar \(H_0\) si

\[z_0=1.25\leq z_{\alpha}=z_{0.05}=-1.6448536,\]

como NO se cumple la condición concluimos que NO podemos rechazar
\(H_0\) contra \(H_1\); la muestra no da evidencias suficientes para
considerar que \(\mu< 60\) al nivel de significación \(\alpha=0.05\).

Por último el \(p\)-valor para esta alternativa es

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p_valor=}\KeywordTok{pnorm}\NormalTok{(z0) }\CommentTok{# 2 P(>>|z0|)}
\NormalTok{p_valor}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.8943502
\end{verbatim}

Como el nivel del significación \(\alpha=0.05\) es menor que el
\(p\)-valor=0.8943502 no podemos rechazar la hipótesis nula.

\hypertarget{ejercicio-2}{%
\subsection{Ejercicio 2}\label{ejercicio-2}}

Hemos obtenido una media muestral de \(\overline{x}=72.5\) de una
muestra aleatoria simple de tamaño \(n=100\) extraída de una población
normal con \(\sigma^2=30^2\). Contrastar al nivel de significación
\(\alpha=0.10\), la hipótesis nula \(\mu=77\) contra las siguientes tres
alternativas \(\mu\not= 70\), \(\mu>70\), \(\mu<70\). Calcular el
\(p\)-valor en cada caso.

\hypertarget{soluciuxf3n-1}{%
\subsubsection{Solución}\label{soluciuxf3n-1}}

Tenemos que contrastar \(\mu=70\) con cada una (por separado) de las
tres alternativas, la población es normal los contrastes son:

\[
\left\{
\begin{array}{ll}
H_{0}:\mu=70\\
H_{1}:\mu\not= 70, \mu>70 , \mu<70
\end{array}
\right.
\]

Cargamos los datos del enunciado

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sigma2=}\DecValTok{30}\OperatorTok{^}\DecValTok{2}
\NormalTok{sigma2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 900
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sigma=}\KeywordTok{sqrt}\NormalTok{(sigma2)}
\NormalTok{sigma}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 30
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n=}\DecValTok{100}
\NormalTok{n}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 100
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{media_muestral=}\FloatTok{72.5}
\NormalTok{media_muestral}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 72.5
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{alpha=}\FloatTok{0.1}
\NormalTok{alpha}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mu0=}\DecValTok{70}
\NormalTok{mu0}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 70
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{z0 =}\StringTok{ }\NormalTok{(media_muestral}\OperatorTok{-}\NormalTok{mu0)}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(sigma2}\OperatorTok{/}\NormalTok{n)}
\NormalTok{z0}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.8333333
\end{verbatim}

Bajo estas condiciones, normalidad muestra aleatoria simple y esto datos
el estadístico de contraste es

\[z_0=\frac{\overline{x}-\mu_0}{\frac{\sigma}{\sqrt{n}}}=
\frac{72.5-70}{\frac{30}{\sqrt{100}}}
=0.8333333\]

Ahora para cada opción alternativa los valores críticos son

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#valores crítico para mu  distinto de 70}
\NormalTok{valor_critico_bilateral=}\StringTok{ }\KeywordTok{c}\NormalTok{(}\OperatorTok{-}\KeywordTok{qnorm}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\NormalTok{alpha}\OperatorTok{/}\DecValTok{2}\NormalTok{), }\KeywordTok{qnorm}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\NormalTok{alpha}\OperatorTok{/}\DecValTok{2}\NormalTok{))}
\NormalTok{valor_critico_bilateral }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -1.644854  1.644854
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#valores crítico para mu   menor  70}
\NormalTok{valor_critico_unilateral_menor=}\StringTok{ }\KeywordTok{qnorm}\NormalTok{(alpha)}
\NormalTok{valor_critico_unilateral_menor }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -1.281552
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#valores crítico para mu  distinto de 70}
\NormalTok{valor_critico_unilateral_mayor=}\StringTok{ }\KeywordTok{qnorm}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\NormalTok{alpha)}
\NormalTok{valor_critico_unilateral_mayor}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.281552
\end{verbatim}

Ahora tenemos tres casos según \(H_1\):

\begin{itemize}
\tightlist
\item
  \(H_1: \mu \not= 70\) como \(z_0= 0.8333333 \not< -1.6448536\) y
  \(z_0= 0.8333333 \not > 1.6448536\) \textbf{NO se cumple la condición
  de rechazo} así que NO podemos rechazar \(H_0\) contra \(H_1\); la
  muestra no da evidencias suficientes para considerar que
  \(\mu\not= 70\) al nivel de significación \(\alpha=0.1\).
\item
  \(H_1: \mu < 70\) como \(z_0= 0.8333333 \not<-1.2815516\) \textbf{NO
  se cumple la condición de rechazo} así que NO podemos rechazar
  \(H_0:\mu=70\) contra \(H_1:\mu<70\); la muestra no da evidencias
  suficientes para considerar que \(\mu < 70\) al nivel de significación
  \(\alpha=0.1\).
\item
  \(H_1: \mu > 70\) como \(z_0= 0.8333333 \not >1.2815516\) \textbf{NO
  se cumple la condición de rechazo} así que no podemos rechazar
  \(H_0:\mu=70\) en favor de que \(H_1:\mu>70\); la muestra no da
  algunas evidencias suficientes para considerar que \(\mu > 70\) al
  nivel de significación \(\alpha=0.1\).
\end{itemize}

Para cada hipótesis alternativa los \(p\)-valores son :

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{2}\OperatorTok{*}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\KeywordTok{pnorm}\NormalTok{(}\KeywordTok{abs}\NormalTok{(z0))) }\CommentTok{# Para H_1: mu != 70}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.4046568
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{pnorm}\NormalTok{(z0) }\CommentTok{# para H_1: mu<70}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.7976716
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{1}\OperatorTok{-}\KeywordTok{pnorm}\NormalTok{(z0) }\CommentTok{# para H_1: mu>70}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.2023284
\end{verbatim}

Como el nivel del significación es \(\alpha=0.05\) es menor que el
\(p\)-valor en cualquiera de los tres casos no podemos rechazar la
hipótesis nula.

\hypertarget{ejercicio-3}{%
\subsection{Ejercicio 3}\label{ejercicio-3}}

En un contraste bilateral, con \(\alpha=0.01\), ¿para qué valores de
\(\overline{X}\) rechazaríamos la hipótesis nula \(H_{0}:\mu=70\), a
partir de una muestra aleatoria simple de tamaño \(n=64\) extraída de
una población normal con \(\sigma^2=16^2\)?

\hypertarget{soluciuxf3n-2}{%
\subsubsection{Solución}\label{soluciuxf3n-2}}

Cargamos los datos, la población es normal

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sigma2=}\DecValTok{16}\OperatorTok{^}\DecValTok{2}
\NormalTok{sigma2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 256
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n=}\DecValTok{64}
\NormalTok{n}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 64
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{alpha=}\FloatTok{0.01}
\NormalTok{alpha}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.01
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mu0=}\DecValTok{70}
\NormalTok{mu0}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 70
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{z0 =}\StringTok{ }\NormalTok{(media_muestral}\OperatorTok{-}\NormalTok{mu0)}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(sigma2}\OperatorTok{/}\NormalTok{n)}
\NormalTok{z0}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.25
\end{verbatim}

Bajo estas condiciones, normalidad muestra aleatoria simple y esto datos
el estadístico de contraste es

\[z_0=\frac{\overline{x}-\mu_0}{\frac{\sigma}{\sqrt{n}}}=
\frac{72.5-70}{\frac{16}{\sqrt{64}}}
=1.25\]

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#valores crítico para \textbackslash{}mu  distinto de 70}
\NormalTok{valor_critico_bilateral=}\StringTok{ }\KeywordTok{c}\NormalTok{(}\KeywordTok{qnorm}\NormalTok{(alpha}\OperatorTok{/}\DecValTok{2}\NormalTok{), }\KeywordTok{qnorm}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\NormalTok{alpha}\OperatorTok{/}\DecValTok{2}\NormalTok{))}
\NormalTok{valor_critico_bilateral}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -2.575829  2.575829
\end{verbatim}

Por lo tanto rechazaremos la hipótesis nula si
\(z_0=\frac{\overline{x}-70}{\frac{16}{\sqrt{64}}} < -2.5758293\) o
\(z_0=\frac{\overline{x}-70}{\frac{16}{\sqrt{64}}} > 2.5758293\)

Despejando \(\overline{x}\) de las inecuaciones anteriores obtenemos que
rechazaremos \(H_0\) si

\(\overline{x}<70 + -2.5758293\cdot \frac{16}{\sqrt{64}}\) o
\(\overline{x}>70 + 2.5758293\cdot \frac{16}{\sqrt{64}}\).

Es decir si \(\overline{x}<64.8483414\) o \(\overline{x}>75.1516586\)
rechazaremos la hipótesis nula al nivel de confianza del \(1\%\)
(\(\alpha=0.1\)).

\hypertarget{ejercicio-4}{%
\subsection{Ejercicio 4}\label{ejercicio-4}}

El salario anual medio de una muestra de tamaño \(n= 1600\) personas,
elegidas aleatoria e independientemente de cierta población de
profesionales de las Tecnologías de la Información y Comunicación (TIC)
ha sido de de 45000 euros, supongamos que nos dicen que la desviación
típica es \(\sigma=2000\) euros

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  ¿Es compatible con este resultado la hipótesis nula,
  \(H_{0}:\mu=43500\) contra la alternativa bilateral, al nivel de
  significación \(\alpha=0.01\)?
\item
  ¿Cuál es el intervalo de confianza para \(\mu\)?
\item
  Calcular el \(p\)-valor del contraste.
\end{enumerate}

\hypertarget{soluciuxf3n-3}{%
\subsubsection{Solución}\label{soluciuxf3n-3}}

Cargamos datos

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n=}\DecValTok{1600}
\NormalTok{n}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1600
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sigma=}\DecValTok{4000}
\NormalTok{sigma}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4000
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sigma2=sigma}\OperatorTok{^}\DecValTok{2}
\NormalTok{sigma2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 16000000
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{media_muestral=}\DecValTok{45000}
\NormalTok{media_muestral}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 45000
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{alpha=}\FloatTok{0.01}
\NormalTok{alpha}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.01
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mu0=}\DecValTok{44900}
\NormalTok{mu0}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 44900
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{z0 =}\StringTok{ }\NormalTok{(media_muestral}\OperatorTok{-}\NormalTok{mu0)}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(sigma2}\OperatorTok{/}\NormalTok{n)}
\NormalTok{z0}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1
\end{verbatim}

Para la primera y la tercera cuestión calculo el \(p\)-valor

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{2}\OperatorTok{*}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\KeywordTok{pnorm}\NormalTok{(}\KeywordTok{abs}\NormalTok{(z0)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.3173105
\end{verbatim}

Es un \(p\)-valor alto así que no podemos rechazar la hipótesis nula.

En la cuestión 2 nos piden intervalo de confianza para \(\mu\) al nivel
del \(\alpha=0.01\) es

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{IC=}\KeywordTok{c}\NormalTok{(media_muestral}\OperatorTok{-}\KeywordTok{qnorm}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\NormalTok{alpha}\OperatorTok{/}\DecValTok{2}\NormalTok{)}\OperatorTok{*}\NormalTok{sigma}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(n),}
\NormalTok{     media_muestral}\OperatorTok{+}\KeywordTok{qnorm}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\NormalTok{alpha}\OperatorTok{/}\DecValTok{2}\NormalTok{)}\OperatorTok{*}\NormalTok{sigma}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(n))}
\NormalTok{IC}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 44742.42 45257.58
\end{verbatim}

Con un nivel de confianza del \(99\%\) la media poblacional del sueldo
mensual en euros de un empleo TIC está en el intervalo
\((44742.4170696, 45257.5829304).\)

\hypertarget{ejercicio-5-extra-voluntario}{%
\subsection{Ejercicio 5 EXTRA
VOLUNTARIO}\label{ejercicio-5-extra-voluntario}}

Con los datos del ejercicio anterior, ¿hay evidencia sobre para oponerse
la hipótesis nula en los siguientes casos

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \(\left\{\begin{array}{ll} H_{0}:\mu=44000\\ H_{1}:\mu>44000\end{array}\right.\)
\item
  \(\left\{\begin{array}{ll} H_{0}:\mu=46250\\ H_{1}:\mu>46250\end{array}\right.\)
\end{enumerate}

\hypertarget{soluciuxf3n-4}{%
\subsubsection{Solución}\label{soluciuxf3n-4}}

Es similar a los ejercicios anteriores

\hypertarget{ejercicio-6-extra-voluntario}{%
\subsection{Ejercicio 6 EXTRA
VOLUNTARIO}\label{ejercicio-6-extra-voluntario}}

El peso medio de los paquetes de mate puestos a la venta por la casa
comercial MATEASA es supuestamente de 1 Kg. Para comprobar esta
suposición, elegimos una muestra aleatoria simple de 100 paquetes y
encontramos que su peso medio es de 0.978 Kg. y su desviación típica
\(s=0.10\) kg. Siendo \(\alpha=0.05\) ¿es compatible este resultado con
la hipótesis nula \(H_{0}:\mu=1\) frente a \(H_{1}:\mu\not=1\)? ¿Lo es
frente a \(H_{1}:\mu>1\)? Calcular el \(p\)-valor.

\hypertarget{soluciuxf3n-5}{%
\subsubsection{Solución}\label{soluciuxf3n-5}}

Es similar a los ejercicios anteriores

\end{document}
