% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames*,x11names*}{xcolor}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Ejercicios Tema 4 - Contraste hipótesis. Taller 2},
  pdfauthor={Ricardo Alberich, Juan Gabriel Gomila y Arnau Mir},
  colorlinks=true,
  linkcolor=red,
  filecolor=Maroon,
  citecolor=blue,
  urlcolor=blue,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\renewcommand{\contentsname}{Contenidos}

\title{Ejercicios Tema 4 - Contraste hipótesis. Taller 2}
\author{Ricardo Alberich, Juan Gabriel Gomila y Arnau Mir}
\date{Curso completo de estadística inferencial con R y Python}

\begin{document}
\maketitle

{
\hypersetup{linkcolor=blue}
\setcounter{tocdepth}{2}
\tableofcontents
}
\hypertarget{contraste-hipuxf3tesis-taller-2.}{%
\section{Contraste hipótesis taller
2.}\label{contraste-hipuxf3tesis-taller-2.}}

\hypertarget{ejercicio-1}{%
\subsection{Ejercicio 1}\label{ejercicio-1}}

EL iris data set es una colección clásica de datos. En este data set hay
150 flores de tres especies las que se mide la longitud y anchura de sus
pétalos y sépalos.

La medias globales de toda la población son

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(tidyverse)}
\NormalTok{resumen1=iris }\OperatorTok{%>%}\StringTok{ }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{Media_Sepal.Length=}\KeywordTok{mean}\NormalTok{(Sepal.Length),Desviación_}\DataTypeTok{muestral=}\KeywordTok{sd}\NormalTok{(Sepal.Length))}
\NormalTok{resumen1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Media_Sepal.Length Desviación_muestral
## 1           5.843333           0.8280661
\end{verbatim}

Consideremos una muestra de tamaño \(n=50\) de la longitud del sépalo
del dataset iris que generamos con el siguiente código

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{set.seed}\NormalTok{(}\DecValTok{333}\NormalTok{)}\CommentTok{# para fijar la muestra}
\NormalTok{muestra_}\DecValTok{50}\NormalTok{=}\KeywordTok{sample}\NormalTok{(iris}\OperatorTok{$}\NormalTok{Sepal.Length,}\DataTypeTok{size=}\DecValTok{50}\NormalTok{,}\DataTypeTok{replace =} \OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Contrastar si podemos aceptar que la media de la muestra es igual a la
  media poblacional es igual a \(5.5\) contra que es distinta, resolver
  utilizando el \(p\)-valor.
\item
  Calcular un intervalo de confianza del tipo \((-\infty,x_0)\) para la
  media poblacional de la muestra al nivel de confianza del 95\%
\end{enumerate}

\hypertarget{soluciuxf3n}{%
\subsubsection{Solución}\label{soluciuxf3n}}

Para la primera cuestión y bajo estas condiciones, \(n=50\) muestra
grande \$ varianza desconocida podemos utilizar un \(t\)-test

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{t.test}\NormalTok{(muestra_}\DecValTok{50}\NormalTok{,}\DataTypeTok{mu=}\FloatTok{5.5}\NormalTok{,}\DataTypeTok{alternative =} \StringTok{"two.sided"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  One Sample t-test
## 
## data:  muestra_50
## t = 3.3027, df = 49, p-value = 0.001793
## alternative hypothesis: true mean is not equal to 5.5
## 95 percent confidence interval:
##  5.654262 6.133738
## sample estimates:
## mean of x 
##     5.894
\end{verbatim}

El \(p\)-valor del contraste es c(t = 3.3026648158547), c(df = 49),
0.00179334930855166, c(5.65426248875515, 6.13373751124485),
c(\texttt{mean\ of\ x} = 5.894), c(mean = 5.5), 0.11929760419785,
two.sided, One Sample t-test, muestra\_50 muy pequeño así que no podemos
rechazar que la media sea \(5.5\) (fijémosnos que media real es
\(5.843333\))

Para la segunda cuestión podemos utilizar la función t.test

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{t.test}\NormalTok{(muestra_}\DecValTok{50}\NormalTok{,}\DataTypeTok{alternative=}\StringTok{"less"}\NormalTok{,}\DataTypeTok{conf.level=}\FloatTok{0.95}\NormalTok{)}\OperatorTok{$}\NormalTok{conf.int}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]     -Inf 6.094009
## attr(,"conf.level")
## [1] 0.95
\end{verbatim}

\hypertarget{ejercicio-2}{%
\subsection{Ejercicio 2}\label{ejercicio-2}}

Hemos obtenido una media muestral de \(\overline{x}=72.5\) de una
muestra aleatoria simple de tamaño \(n=100\) extraída de una población
normal con \(\sigma^2=30^2\). Contrastar al nivel de significación
\(\alpha=0.10\), la hipótesis nula \(\mu=77\) contra las siguientes tres
alternativas \(\mu\not= 70\), \(\mu>70\), \(\mu<70\). Calcular el
\(p\)-valor en cada caso.

\hypertarget{ejercicio-3}{%
\subsection{Ejercicio 3}\label{ejercicio-3}}

En un contraste bilateral, con \(\alpha=0.01\), ¿para qué valores de
\(\overline{X}\) rechazaríamos la hipótesis nula \(H_{0}:\mu=70\), a
partir de una muestra aleatoria simple de tamaño \(n=64\) extraída de
una población normal con \(\sigma^2=16^2\)?

\hypertarget{ejercicio-4}{%
\subsection{Ejercicio 4}\label{ejercicio-4}}

El salario anual medio de una muestra de tamaño \(n= 1600\) personas,
elegidas aleatoria e independientemente de cierta población de
profesionales de las Tecnologías de la Información y Comunicación (TIC)
ha sido de de 45000 euros, supongamos que nos dicen que la desviación
típica es \(\sigma=2000\) euros

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  ¿Es compatible con este resultado la hipótesis nula,
  \(H_{0}:\mu=43500\) contra la alternativa bilateral, al nivel de
  significación \(\alpha=0.01\)?
\item
  ¿Cuál es el intervalo de confianza para \(\mu\)?
\item
  Calcular el \(p\)-valor del contraste.
\end{enumerate}

\hypertarget{ejercicio-5-extra-voluntario}{%
\subsection{Ejercicio 5 EXTRA
VOLUNTARIO}\label{ejercicio-5-extra-voluntario}}

Con los datos del ejercicio anterior, ¿hay evidencia sobre para oponerse
la hipótesis nula en los siguientes casos

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \(\left\{\begin{array}{ll} H_{0}:\mu=44000\\ H_{1}:\mu>44000\end{array}\right.\)
\item
  \(\left\{\begin{array}{ll} H_{0}:\mu=46250\\ H_{1}:\mu>46250\end{array}\right.\)
\end{enumerate}

\hypertarget{ejercicio-6-extra-voluntario}{%
\subsection{Ejercicio 6 EXTRA
VOLUNTARIO}\label{ejercicio-6-extra-voluntario}}

El peso medio de los paquetes de mate puestos a la venta por la casa
comercial MATEASA es supuestamente de 1 Kg. Para comprobar esta
suposición, elegimos una muestra aleatoria simple de 100 paquetes y
encontramos que su peso medio es de 0.978 Kg. y su desviación típica
\(s=0.10\) kg. Siendo \(\alpha=0.05\) ¿es compatible este resultado con
la hipótesis nula \(H_{0}:\mu=1\) frente a \(H_{1}:\mu\not=1\)? ¿Lo es
frente a \(H_{1}:\mu>1\)? Calcular el \(p\)-valor.

\end{document}
