---
title: "Ejercicios Tema 3 - Intervalos de Confianza. Taller 1"
author: "Ricardo Alberich, Juan Gabriel Gomila y Arnau Mir"
date: "Curso completo de estadística inferencial con R y Python"
output:
  pdf_document:
    number_sections: yes
    toc: yes
  html_document:
    df_print: paged
    toc: yes
linkcolor: red
header-includes: \renewcommand{\contentsname}{Contenidos}
citecolor: blue
toccolor: blue
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Estimación por intervalos taller 1

## Ejercicio 1

De una población de barras de hierro se extrae una muestra de $64$ barras y  se calcula la
resistencia a la rotura por tracción se obtiene que $\overline{X}=1012\ Kg/cm^{2}$. Se sabe
por experiencia que en este tipo de barras $\sigma=25$ y que la resistencia a la rotura sigue la distribución normal. Calcular un intervalo de confianza
para $\mu$ al nivel 0.95. 


## Ejercicio 2

Para investigar el C.I. medio de una cierta población de estudiantes, se realiza un test a
$400$ estudiantes. La media y la desviación típica  muestrales obtenidas son
$\overline{x}=86$ y $\tilde{s}_{X}=10.2$. Calcular un intervalo para $\mu$ con un nivel de
significación del 98\%.

## Ejercicio 3

Para investigar un nuevo tipo de combustible para cohetes espaciales, se disparan cuatro
unidades y se miden las velocidades iniciales. Los resultados obtenidos, expresados en
Km/h, son :19600, 20300, 20500, 19800. Calcular un intervalo para la velocidad media $\mu$
con un nivel de confianza del 95\%, suponiendo que las velocidades son normales.



## Ejercicio 4 

Un fabricante de cronómetros quiere calcular un intervalo de estimación de la desviación
típica del tiempo marcado en $100$ horas por todos los cronómetros  de un cierto modelo.
Para ello pone en marcha $10$ cronómetros del modelo durante $100$ horas y encuentra que
$\tilde{s}_{X}=50$ segundos. Encontrar un intervalo para el parámetro $\sigma^2$ con
$\alpha=0.01$, suponiendo que la población del tiempo marcado por los cronómetros es
normal. 

## Ejercicio 5

Un auditor informático quiere investigar la proporción de rutinas de un programa que
presentan una determinada irregularidad. Para ello observa $120$ rutinas, resultando que
$30$ de ellas presentan alguna irregularidad. Con estos datos buscar unos límites de
confianza para la proporción $p$ de rutinas de la población que presentan esa irregularidad
con probabilidad del 95\%.


