% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames*,x11names*}{xcolor}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Ejercicios Tema 3 - Intervalos de Confianza. Taller 1},
  pdfauthor={Ricardo Alberich, Juan Gabriel Gomila y Arnau Mir},
  colorlinks=true,
  linkcolor=red,
  filecolor=Maroon,
  citecolor=blue,
  urlcolor=blue,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\renewcommand{\contentsname}{Contenidos}

\title{Ejercicios Tema 3 - Intervalos de Confianza. Taller 1}
\author{Ricardo Alberich, Juan Gabriel Gomila y Arnau Mir}
\date{Curso completo de estadística inferencial con R y Python}

\begin{document}
\maketitle

{
\hypersetup{linkcolor=blue}
\setcounter{tocdepth}{4}
\tableofcontents
}
\hypertarget{estimaciuxf3n-por-intervalos-taller-1}{%
\section{Estimación por intervalos taller
1}\label{estimaciuxf3n-por-intervalos-taller-1}}

\hypertarget{ejercicio-1}{%
\subsection{Ejercicio 1}\label{ejercicio-1}}

De una población de barras de hierro se extrae una muestra de \(64\)
barras y se calcula la resistencia a la rotura por tracción se obtiene
que \(\overline{X}=1012\ Kg/cm^{2}\). Se sabe por experiencia que en
este tipo de barras \(\sigma=25\) y que la resistencia a la rotura sigue
la distribución normal. Calcular un intervalo de confianza para \(\mu\)
al nivel 0.95.

\hypertarget{soluciuxf3n}{%
\subsubsection{Solución}\label{soluciuxf3n}}

El intervalo para la media es

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n=}\DecValTok{64}
\NormalTok{xmedia=}\DecValTok{1012}
\NormalTok{sigma=}\DecValTok{25}
\NormalTok{alpha=}\DecValTok{1}\FloatTok{{-}0.95}
\NormalTok{IC=}\KeywordTok{c}\NormalTok{(xmedia}\OperatorTok{{-}}\KeywordTok{qnorm}\NormalTok{(}\DecValTok{1}\OperatorTok{{-}}\NormalTok{alpha}\OperatorTok{/}\DecValTok{2}\NormalTok{)}\OperatorTok{*}\NormalTok{sigma}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(n),xmedia}\OperatorTok{+}\KeywordTok{qnorm}\NormalTok{(}\DecValTok{1}\OperatorTok{{-}}\NormalTok{alpha}\OperatorTok{/}\DecValTok{2}\NormalTok{)}\OperatorTok{*}\NormalTok{sigma}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(n))}
\NormalTok{IC}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1005.875 1018.125
\end{verbatim}

Con un nivel de confianza del \(95\%\) el intervalo
\((1005.8751125, 1018.1248875)\) contiene el verddero valor de la
ressitencia a la rotura de estas barras de hierro.

\hypertarget{ejercicio-2}{%
\subsection{Ejercicio 2}\label{ejercicio-2}}

Para investigar el C.I. medio de una cierta población de estudiantes, se
realiza un test a \(400\) estudiantes. La media y la desviación típica
muestrales obtenidas son \(\overline{x}=86\) y \(\tilde{s}_{X}=10.2\).
Calcular un intervalo para \(\mu\) con un nivel de significación del
98\%.

\hypertarget{soluciuxf3n-1}{%
\subsubsection{Solución}\label{soluciuxf3n-1}}

Como el tamaño de la muestra es grande aproximaremos por una
distribución normal aproximando la desviación típica poblacional por la
muestral. El intervalo obtenido es

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n=}\DecValTok{400}
\NormalTok{xmedia=}\DecValTok{86}
\NormalTok{stilde=}\FloatTok{10.2}
\NormalTok{alpha=}\DecValTok{1}\FloatTok{{-}0.98}
\NormalTok{IC=}\KeywordTok{c}\NormalTok{(xmedia}\OperatorTok{{-}}\KeywordTok{qnorm}\NormalTok{(}\DecValTok{1}\OperatorTok{{-}}\NormalTok{alpha}\OperatorTok{/}\DecValTok{2}\NormalTok{)}\OperatorTok{*}\NormalTok{stilde}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(n),xmedia}\OperatorTok{+}\KeywordTok{qnorm}\NormalTok{(}\DecValTok{1}\OperatorTok{{-}}\NormalTok{alpha}\OperatorTok{/}\DecValTok{2}\NormalTok{)}\OperatorTok{*}\NormalTok{stilde}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(n))}
\NormalTok{IC}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 84.81356 87.18644
\end{verbatim}

Con un nivel de confianza del \(98\%\) el intervalo
\((84.8136, 87.1864)\) contiene cpntredrá la media poblacional del C.I.
de los estudiantes.

\hypertarget{ejercicio-3}{%
\subsection{Ejercicio 3}\label{ejercicio-3}}

Para investigar un nuevo tipo de combustible para cohetes espaciales, se
disparan cuatro unidades y se miden las velocidades iniciales. Los
resultados obtenidos, expresados en Km/h, son :19600, 20300, 20500,
19800. Calcular un intervalo para la velocidad media \(\mu\) con un
nivel de confianza del 95\%, suponiendo que las velocidades son
normales.

\hypertarget{soluciuxf3n-2}{%
\subsubsection{Solución}\label{soluciuxf3n-2}}

En este caso nos dicen que la población sigue una distribución normal y
que el tamañó de la muestra \(n=4\) es pequeño, así que utilizremos la
\(t\) de Student para el cálculo de los cuantiles de intervalo.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n=}\DecValTok{4}
\NormalTok{muestra=}\KeywordTok{c}\NormalTok{(}\DecValTok{19600}\NormalTok{, }\DecValTok{20300}\NormalTok{, }\DecValTok{20500}\NormalTok{, }\DecValTok{19800}\NormalTok{)}
\NormalTok{xmedia=}\KeywordTok{mean}\NormalTok{(muestra)}
\NormalTok{xmedia}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 20050
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{stilde=}\KeywordTok{sd}\NormalTok{(muestra)}
\NormalTok{stilde}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 420.3173
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{alpha=}\DecValTok{1}\FloatTok{{-}0.95}
\NormalTok{IC=}\KeywordTok{c}\NormalTok{(xmedia}\OperatorTok{{-}}\KeywordTok{qt}\NormalTok{(}\DecValTok{1}\OperatorTok{{-}}\NormalTok{alpha}\OperatorTok{/}\DecValTok{2}\NormalTok{,}\DataTypeTok{df=}\NormalTok{n}\DecValTok{{-}1}\NormalTok{)}\OperatorTok{*}\NormalTok{stilde}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(n),xmedia}\OperatorTok{+}\KeywordTok{qt}\NormalTok{(}\DecValTok{1}\OperatorTok{{-}}\NormalTok{alpha}\OperatorTok{/}\DecValTok{2}\NormalTok{,}\DataTypeTok{df=}\NormalTok{n}\DecValTok{{-}1}\NormalTok{)}\OperatorTok{*}\NormalTok{stilde}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(n))}
\NormalTok{IC}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 19381.18 20718.82
\end{verbatim}

Al nivel de confianza del \(95\%\) el intervalo
\((19381.1813165, 20718.8186835)\) contiene el verdadero valor de la
velocidad media de estos cohetes.

\hypertarget{ejercicio-4}{%
\subsection{Ejercicio 4}\label{ejercicio-4}}

Un fabricante de cronómetros quiere calcular un intervalo de estimación
de la desviación típica del tiempo marcado en \(100\) horas por todos
los cronómetros de un cierto modelo. Para ello pone en marcha \(10\)
cronómetros del modelo durante \(100\) horas y encuentra que
\(\tilde{s}_{X}=50\) segundos. Encontrar un intervalo para el parámetro
\(\sigma^2\) con \(\alpha=0.01\), suponiendo que la población del tiempo
marcado por los cronómetros es normal.

\hypertarget{soluciuxf3n-3}{%
\subsubsection{Solución}\label{soluciuxf3n-3}}

Ekl tamaño de la muestra \(n=10\) no es muy grande pero este caso la
distribución poblacional del tiempo es normal .

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n=}\DecValTok{10}
\NormalTok{stilde=}\DecValTok{50}
\NormalTok{alpha=}\FloatTok{0.01} \CommentTok{\# nivel de confianza del 99\% }
\NormalTok{IC=}\KeywordTok{c}\NormalTok{((n}\DecValTok{{-}1}\NormalTok{)}\OperatorTok{*}\NormalTok{stilde}\OperatorTok{\^{}}\DecValTok{2}\OperatorTok{/}\KeywordTok{qchisq}\NormalTok{(}\DecValTok{1}\OperatorTok{{-}}\NormalTok{alpha}\OperatorTok{/}\DecValTok{2}\NormalTok{,}\DataTypeTok{df =}\NormalTok{ n}\DecValTok{{-}1}\NormalTok{),(n}\DecValTok{{-}1}\NormalTok{)}\OperatorTok{*}\NormalTok{stilde}\OperatorTok{\^{}}\DecValTok{2}\OperatorTok{/}\KeywordTok{qchisq}\NormalTok{(alpha}\OperatorTok{/}\DecValTok{2}\NormalTok{,}\DataTypeTok{df =}\NormalTok{ n}\DecValTok{{-}1}\NormalTok{))}
\NormalTok{IC}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]   953.8202 12968.8012
\end{verbatim}

Al nivel de confianza del \(99\%\) el intervalo
\((953.8202305, 12968.8012344)\) contiene el verdadero valor de la
varianza \(\sigma^2\) del tiempo.

\hypertarget{ejercicio-5}{%
\subsection{Ejercicio 5}\label{ejercicio-5}}

Un auditor informático quiere investigar la proporción de rutinas de un
programa que presentan una determinada irregularidad. Para ello observa
\(120\) rutinas, resultando que \(30\) de ellas presentan alguna
irregularidad. Con estos datos buscar unos límites de confianza para la
proporción \(p\) de rutinas de la población que presentan esa
irregularidad con probabilidad del 95\%.

\hypertarget{soluciuxf3n-4}{%
\subsubsection{Solución}\label{soluciuxf3n-4}}

En este problema podemos utilizar distintas aproximaciones el intervalo.
Siempre es mejor la exacta pero es posible que, para muestras grandes,
tengan menor error de cálculo las soluciones aproximadas.

Calculemos varias de ellas; empecemos cargando los datos del problema:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n=}\DecValTok{120}
\NormalTok{n}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 120
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x=}\DecValTok{30}\CommentTok{\# datos bernoulli a 1 }
\NormalTok{x}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 30
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p\_muestral=x}\OperatorTok{/}\NormalTok{n  }\CommentTok{\# proporción muestral}
\NormalTok{p\_muestral}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.25
\end{verbatim}

\begin{itemize}
\tightlist
\item
  Método exacto Cloper Pearson
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#install.packages("epitools") \# descomentar para intalar epitools}
\NormalTok{epitools}\OperatorTok{::}\KeywordTok{binom.exact}\NormalTok{(}\DataTypeTok{x=}\NormalTok{x,}\DataTypeTok{n=}\NormalTok{n,}\DataTypeTok{conf.level=}\FloatTok{0.95}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    x   n proportion     lower     upper conf.level
## 1 30 120       0.25 0.1754646 0.3372692       0.95
\end{verbatim}

\begin{itemize}
\tightlist
\item
  Método de Wilson
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{epitools}\OperatorTok{::}\KeywordTok{binom.wilson}\NormalTok{(x,n,}\DataTypeTok{conf.level=}\FloatTok{0.95}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    x   n proportion     lower     upper conf.level
## 1 30 120       0.25 0.1810982 0.3344114       0.95
\end{verbatim}

\begin{itemize}
\tightlist
\item
  Aproximación normal fórmula de Laplace
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{epitools}\OperatorTok{::}\KeywordTok{binom.approx}\NormalTok{(x,n,}\DataTypeTok{conf.level=}\FloatTok{0.95}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    x   n proportion     lower     upper conf.level
## 1 30 120       0.25 0.1725256 0.3274744       0.95
\end{verbatim}

En este caso la podemos reproducir el cáculo de forma sencilla con
funciones básicas de R

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{alpha=}\DecValTok{1}\FloatTok{{-}0.95}
\NormalTok{IC=}\KeywordTok{c}\NormalTok{(p\_muestral}\OperatorTok{{-}}\KeywordTok{qnorm}\NormalTok{(}\DecValTok{1}\OperatorTok{{-}}\NormalTok{alpha}\OperatorTok{/}\DecValTok{2}\NormalTok{)}\OperatorTok{*}\KeywordTok{sqrt}\NormalTok{(p\_muestral}\OperatorTok{*}\NormalTok{(}\DecValTok{1}\OperatorTok{{-}}\NormalTok{p\_muestral)}\OperatorTok{/}\NormalTok{n),}
\NormalTok{     p\_muestral}\OperatorTok{+}\KeywordTok{qnorm}\NormalTok{(}\DecValTok{1}\OperatorTok{{-}}\NormalTok{alpha}\OperatorTok{/}\DecValTok{2}\NormalTok{)}\OperatorTok{*}\KeywordTok{sqrt}\NormalTok{(p\_muestral}\OperatorTok{*}\NormalTok{(}\DecValTok{1}\OperatorTok{{-}}\NormalTok{p\_muestral)}\OperatorTok{/}\NormalTok{n))}
\NormalTok{IC}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1725256 0.3274744
\end{verbatim}

\end{document}
