---
title: "Ejercicios Tema 4 - Contraste hipótesis. Taller 1"
author: "Ricardo Alberich, Juan Gabriel Gomila y Arnau Mir"
date: "Curso completo de estadística inferencial con R y Python"
output:
  pdf_document:
    number_sections: yes
    toc: yes
  html_document:
    df_print: paged
    toc: yes
toccolor: blue
linkcolor: red
header-includes: \renewcommand{\contentsname}{Contenidos}
citecolor: blue
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
contador=0
cuenta=function(x=contador) {contador<<- contador+1;return(contador)} 
```


# Contraste hipótesis taller 1


## Ejercicio `r cuenta()`
El fabricante de la marca de tornillos FDE afirma que el diámetro medio de sus tornillos
vale 20 mm. Para comprobar dicha afirmación, extraemos aleatoria e independientemente 16
tornillos , y vemos que la media de sus diámetros  es 22 mm. y la desviación típica 4 mm.
¿Podemos aceptar la pretensión del fabricante, suponiendo $\alpha=0.05$ y siendo el
contraste bilateral? Calcular el $p$-valor.
 

## Ejercicio `r cuenta()`
EL departamento de selección de personal de una importante compañía
discriminan mediante un  cuestionario, diseñado por un gabinete de psicólogos, los aspirantes a trabajar en la empresa.

La varianza del test de selección solía venir siendo $\sigma^2=100$.
Aplicando un nuevo test a una muestra aleatoria simple de tamaño
$n=31$, se obtiene que $\tilde{S}=129$. Suponiendo que la población se
distribuye normalmente, ¿es compatible la hipótesis nula
$H_{0}:\sigma^2=100$, frente a la alternativa $H_{1}:\sigma^2>100$,
con $\alpha=0.01$? Calcular el $p$-valor.
 

## Ejercicio `r cuenta()`
¿Una máquina produce cierto tipo de piezas mecánicas. El tiempo en
¿producirlas se distribuye normalmente con varianza desconocida
¿$\sigma^2$. Elegida una muestra aleatoria simple de 21 de dichas
¿piezas ($x_{1},\ldots,x_{21}$), se obtiene que $\overline{x}=30$ y
¿$\sum_{i=1}^{21}x_{i}^2=19100.$ Comprobar si es compatible la
¿hipótesis nula $H_{0}:\sigma^2=22$ frente $H_{1}:\sigma^2\not=22$,
¿con $\alpha=0.1$, y construir un intervalo de confianza del
¿$(1-\alpha)100\%$ para el verdadero valor de $\sigma^2$. Calcular el $p$-valor.
 

## Ejercicio `r cuenta()`
A partir de las puntuaciones 15, 22, 20, 21, 19 ,23, construir el intervalo de confianza de
$\sigma^2$ y decir si es compatible con estos resultado la hipótesis $H_{0}:\sigma=2$,
siendo $\alpha=0.01$ contra una $H_1$ bilateral. Decir si se utiliza alguna hipótesis adicional. Calcular el $p$-valor.
 

## Ejercicio `r cuenta()`
¿Sabiendo que con $\hat{p}=0.52$ ha sido rechazada $H_{0}:p=0.50$, al
¿nivel de significación $\alpha=0.05$, ¿cuál ha tenido que ser el
¿tamaño mínimo de la muestra mediante la cual fue rechazada
¿$H_{0}$

¿ 
¿¿ 1. frente a $H_{1}:p\not=0.5$?
¿ 1. frente a $H_{1}:p>0.5$?
¿ 

¿## Ejercicio `r cuenta()`
¿¿Lanzamos una moneda al aire 10 veces consecutivas . ¿Con qué número
¿¿de caras rechazaremos la hipótesis nula de que la moneda está bien
¿¿balanceada, siendo $\alpha=0.05$?
¿¿ 
 



## Ejercicio `r cuenta()`

Un fabricante de productos farmacéuticos tiene que mantener un estándar de impurezas en el
proceso de producción de sus píldoras. Hasta ahora el número medio poblacional de impurezas
es correcto pero está preocupado porque las impurezas en algunas de las partidas se salen
del rango admitido de forma que provocan devoluciones y posibles reclamaciones por daños a
la salud. El gabinete de control de calidad afirma que si la distribución de las impurezas
es normal y que si el proceso de producción mantiene  una varianza inferior a 1 no tendría
que existir ningún problema pues las píldoras tendrían una concentración aceptable.
Preocupado por esta tema la dirección encarga una prueba externa en la que se toma una
muestra aleatoria de 100 de las partidas obteniéndose $S^2=1.1$. ¿Puede aceptar el director
de la prueba externa que el proceso de producción cumple la recomendación del gabinete de
control?
 


## Ejercicio `r cuenta()`
Un IAP está preocupado por su estándar de calidad y quiere compararlo con el medio europeo.
El estándar medio europeo dice que una empresa de este sector tiene una calidad aceptable
si tiene un número de quejas que no excede del 3\%.

Se sabe que la varianza de las quejas es $0.16$. Examinando $64$ clientes escogidos al azar
se encuentra con que el porcentaje de quejas es del $3.07\%$. Calcular el $p$-valor.

 
¿ 1. Contrastar al nivel de significación del 5\%, la hipótesis nula
¿de que la media poblacional del porcentaje de quejas es del 3\%
¿frente a la alternativa de que es superior al 3\%.
¿ 1. Hallar el $p$-valor del contraste.
¿ 1. Supongamos que la hipótesis alternativa fuese bilateral en
¿lugar de unilateral( con hipótesis nula $H_{0}:\mu=3$). Deducir, sin
¿hacer ningún cálculo, si el $p$-valor del contraste sería mayor,
¿menor o igual que el del apartado anterior. Construir un gráfico
¿para ilustrar el razonamiento.
¿ 1. En el contexto de este problema, explicar por qué una hipótesis
¿alternativa unilateral es más apropiada que una bilateral.
 
 

## Ejercicio `r cuenta()`
A partir de una muestra aleatoria se contrasta:

$$
\left\{\begin{array}{l}
H_{0}:\mu=\mu_{0}\\
H_{1}:\mu>\mu_{0}\end{array}
\right.
$$

 y se acepta la hipótesis nula al nivel de significación del 5\%.

1. ¿Implica esto necesariamente que $\mu_{0}$ está contenido
en el intervalo de confianza del 95\% para $\mu$?
1. Si la media muestral observada es mayor que $\mu_{0}$, ¿implica necesariamente que $\mu_{0}$ está contenido en el intervalo de confianza  del 90\% para $\mu$?
 
 

## Ejercicio `r cuenta()`
Una compañía que se dedica a la venta de franquicias afirma que, por término medio, los
delegados obtienen un redimiendo del 10\% en sus inversiones iniciales. Una muestra
aleatoria de diez de estas franquicias presentaron los siguientes rendimientos el primer
año de operación:

$$6.1, 9.2, 11.5, 8.6, 12.1, 3.9 , 8.4, 10.1, 9.4, 8.9$$

Asumiendo que los rendimientos poblacionales tienen distribución normal, contrastar la
afirmación de la compañía.
 


## Ejercicio `r cuenta()`
Una distribuidora de bebidas refrescantes afirma que una buena fotografía de tamaño real de
un conocido actor, incrementará las ventas de un producto en los supermercados en una media
de $50$ cajas semanales. Para una muestra de $20$ supermercados, el incremento medio fue de
$41.3$ cajas con una desviación típica de $12.2$ cajas. Contrastar al nivel de
significación $\alpha=0.05$, la hipótesis nula de que la media poblacional del incremento
en las ventas es al menos $50$ cajas, indicando cualquier supuesto que se haga. Calcular el
$p$-valor del contraste e interpretarlo.




# Contrastes dos parámetros 




**Comparación de medias.**

Los siguientes problemas tratan de contrastes de parámetros entre dos muestras. Para cada uno de los enunciados contratar contra las  hipótesis unilaterales y bilaterales. Calcular también el intervalo de confianza para la diferencia o el cociente de los parámetros. Tomar finalmente la decisión más correcta. Calcular todos los test e intervalos de confianza para $\alpha=0.05$. Calcular el $p$-valor en cada caso. 

## Ejercicio `r cuenta()`
Para comparar la producción  media de dos procedimientos de fabricación de cierto elemento
se toman dos muestras, una con los elementos fabricados durante 25 días con el primer
método y otra con los producidos durante 16 días con el segundo método. Por experiencia se
sabe que la varianza del primer procedimiento es $\sigma_{1}^2=12$ y al del segundo
$\sigma_{2}^2=10$. De las muestras obtenemos que $\overline{X}_{1}=136$ para el primer
procedimiento y $\overline{X}_{2}=128$ para el segundo. 
% Si $\mu_{1}$ y $\mu_{2}$ son los
% valores esperados para cada uno de los procedimientos, calcular un intervalo de confianza
% para $\mu_{1}-\mu_{2}$ al nivel 99\%. solución {$\left(5.2989,10.7011\right)$}


## Ejercicio `r cuenta()`
Estamos interesados en comparar la vida media, expresada en horas de dos tipos de
componentes electrónicos. Para ello se toma una muestra de cada tipo y se obtiene:

$$
\begin{tabular}{|c|c|c|c|}
\hline Tipo & tamaño & $\overline{X}$ & $S$\\ \hline \hline 1 & 50 & 1260 & 20\\ \hline 2 &
100 & 1240 & 18\\ \hline
\end{tabular}
$$

% Calcular un intervalo de confianza para $\mu_{1}-\mu_{2}$ ($\mu_{1}$ esperanza del primer
% grupo y $\mu_{2}$ esperanza del segundo grupo) al nivel 98\% 
Suponer si es necesario las
poblaciones aproximadamente normales. % solución {$\left(12.19,27.81\right)$}


## Ejercicio `r cuenta()`

Para reducir la concentración de ácido úrico en la sangre se prueban dos drogas. La primera
se aplica a un grupo de 8 pacientes y la segunda a un grupo de 10. Las disminuciones
observadas en las concentraciones de ácido úrico de los distintos pacientes expresadas en
tantos por cien de concentración después de aplicado el tratamiento son:

\begin{center}
\begin{tabular}{|c|c|c|c|c|c|c|c|c|c|c|}
droga 1 & 20 & 12 & 16 & 18 & 13 & 22 & 15 & 20\\ \hline droga 2 & 17 & 14 & 12 & 10 & 15 &
13 & 9 & 19 & 20 & 11
\end{tabular}
\end{center}

% Calcular un intervalo de confianza para la diferencia de medias entre la primera droga y la
% segunda al nivel del 99\%.
 Suponer que las reducciones de ácido úrico siguen una
distribución normal son independientes y de igual varianza. 
Ídem pero suponiendo que las varianza son distintas.%solución {$\left(-2.09,8.09\right)$}


## Ejercicio `r cuenta()`

Para comparar la dureza media de dos tipos de aleaciones (tipo 1 y tipo 2) se hacen 5
pruebas de dureza  con la de tipo 1 y 7 con la de tipo 2. Obteniéndose los resultados
siguientes:
$$\overline{X}_{1}=18.2,\quad S_{1}=0.2 \mbox{ y}$$

$$\overline{X}_{2}=17.8;\quad S_{2}=0.5$$

Suponer que la población de las durezas es normal y que las desviaciones típicas no son
iguales. Hacer lo mismo  si las varianzas son distintas.
% , buscar un intervalo de confianza para $\mu_{1}-\mu_{2}$ con  probabilidad $0.95$
% solución {$\left(0.314,0.486\right)$}




## Ejercicio `r cuenta()` 

Se encuestó a dos muestras independientes de  internautas, una en Menorca y otra en Mallorca, sobre si utilizaban  telefonía por intenet. La encuesta de Menorca tuvo un tamaño $n_1=500$  y 
$100$ usuarios mientras que  en Mallorca se encuestarron a $n_2=750$ y se obtuvo un resultado de $138$ usuarios.


## Ejercicio `r cuenta()`

Se pregunta a un grupo de 100 personas elegido al azar asiste a una conferencia sobre tecnologías de la comunicación. Antes de la conferencia se les pregunta si consideran a internet peligrosa, después de la conferencia se les vuelve a preguntar cual es su opinión. Los resultados fueron los siguientes:

$$
\begin{tabular}{|c|c|cc|}
\cline{3-4}
     \multicolumn{2}{c|}{}& \multicolumn{2}{|c|} {Después}\\\cline{3-4}
   \multicolumn{2}{c|}{} & Sí es peligrosa & No es peligrosa \\\hline
Antes & Sí es peligrosa&  50 &  30 \\
    & No es peligrosa  &  5 & 15 
\\\hline
\end{tabular}
$$




% \hline
% & Antes & Después \\\hline
% Sí es Peligrosa &  80 & 70\\
% No es Peligrosa  & 20 & 30 
% \\\hline
% \end{tabular}




## Ejercicio `r cuenta()` 

Tenemos $10$ ordenadores, deseamos optimizar su funcionamiento. Con este fin  se piensa en ampliar su memoria. Se les pasa una prueba de rendimiento antes  y después de  ampliar la memoria. Los resultados fueron:

$$
\begin{tabular}{|c|llllllllll|}
\hline
 &\multicolumn{10}{|c|}{Ordenador} \\\hline
Muestra\slash Tiempo & 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\\hline
Antes ampliación & 98.70 & 100.48 & 103.75 & 114.41 & 97.82&
91.13 & 85.42 & 96.8 & 107.76 & 112.94\\
\hline
Después ampliación & 99.51 & 114.44 & 108.74 & 97.92 & 103.54&
104.75 & 109.69 & 90.8 & 110.04 & 110.09\\

\hline
\end{tabular}
$$



## Ejercicio `r cuenta()` 

Las siguientes muestras provienen de dos poblaciones independientes y supuestamente normales.  Se desea comparar la igualdan de sus medias, pero antes debemos contrastar si podemos o no aceptar que sus varianza son iguales o distintas. Se pide hacer el contraste de las medias en el caso en que se se decida aceptar varianzas iguales o distintas al nivel de significación $\alpha=0.05$.

Contrastar tambien la hipótesis de igualdad de medias en el otro caso ( es decir si se decide varianzas ditintas contrastar para iguales y viceversa).


## Ejercicio `r cuenta()`

Los candidatos para un puesto de trabajo en una gran empresa deben superar un examen de aptitud escrito y realizar una entrevista con el  director de personal. Después de la entrevista, el director otorga a cada candidato una puntuación entre 0 y 10. 

Para comprobar la consistencia de los criterios de los distintos directores, se extrae una muestra de 10 pares de candidatos. La formación de las parejas se organiza de forma que en cada una de ellas los dos candidatos han obtenido una puntuación idéntica en el examen escrito. Posteriormente, la entrevista a cada uno de los candidatos de cada par es realizada por cada uno de los dos directores de personal, Sr. José y Sra. Isabel. 

Las puntuaciones obtenidas fueron las siguientes:


|Sr. José || 80 | 65 | 87 | 64 | 73 | 78 | 83 | 91 | 84 | 83 |
|..........||....|....|....|....|....|....|....|....|....|....|
|Sra. Isabel || 74 | 63 | 91 | 65 | 64 | 71 | 69 | 90 | 79 | 87|
 

1. Especificando las hipótesis necesarias calcular un intervalo de confianza del 95\ para la diferencia entre las dos puntuaciones medias poblacionales obtenidas (para fijar ideas hacer Sr. José - Sra. Isabel).
1. Sin realizar los cálculos, determinar si un intervalo de confianza al 99\% para la diferencia de las medias poblacionales tendría mayor, menor o la misma amplitud que en el apartado a).
 

