% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames*,x11names*}{xcolor}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Ejercicios Tema 4 - Contraste hipótesis. Taller 3},
  pdfauthor={Ricardo Alberich, Juan Gabriel Gomila y Arnau Mir},
  colorlinks=true,
  linkcolor=red,
  filecolor=Maroon,
  citecolor=blue,
  urlcolor=blue,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\renewcommand{\contentsname}{Contenidos}

\title{Ejercicios Tema 4 - Contraste hipótesis. Taller 3}
\author{Ricardo Alberich, Juan Gabriel Gomila y Arnau Mir}
\date{Curso completo de estadística inferencial con R y Python}

\begin{document}
\maketitle

{
\hypersetup{linkcolor=blue}
\setcounter{tocdepth}{2}
\tableofcontents
}
\hypertarget{contraste-hipuxf3tesis-taller-3.}{%
\section{Contraste hipótesis taller
3.}\label{contraste-hipuxf3tesis-taller-3.}}

\hypertarget{libreruxedas-y-datos-necesarios}{%
\subsection{Librerías y datos
necesarios}\label{libreruxedas-y-datos-necesarios}}

Para este taller necesitaremos los siguientes paquetes:
\texttt{faraway,\ nortest,\ car} si no los tenéis instalados podéis
ejecutar lo siguiente:

\begin{verbatim}
install.packages("faraway")
install.packages("nortest")
install.packages("car")
\end{verbatim}

Para utilizarlos, deberéis cargarlos ejecutando las siguientes
instrucciones:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(}\StringTok{"faraway"}\NormalTok{)}
\KeywordTok{library}\NormalTok{(}\StringTok{"nortest"}\NormalTok{)}
\KeywordTok{library}\NormalTok{(}\StringTok{"car"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{contrastes-de-dos-paruxe1metros.}{%
\section{Contrastes de dos
parámetros.}\label{contrastes-de-dos-paruxe1metros.}}

\textbf{Comparación de medias.}

Los siguientes problemas tratan de contrastes de parámetros entre dos
muestras Para cada uno de los enunciados:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Contrastar contra una de los dos tipos de hipótesis unilaterales o
  bilaterales.
\item
  Calcular también el intervalo de confianza para la diferencia o el
  cociente de los parámetros según el contraste sea bilateral o
  unilateral. Tomar finalmente la decisión más correcta.
\item
  Calcular todos los test e intervalos de confianza para
  \(\alpha=0.05\).
\item
  Calcular el \(p\)-valor en cada caso.
\end{enumerate}

\hypertarget{ejercicio-1}{%
\subsection{Ejercicio 1}\label{ejercicio-1}}

Para comparar la producción media de dos procedimientos de fabricación
de cierto producto se toman dos muestras, una con la cantidad producida
durante 25 días con el primer método y otra con la cantidad producida
durante 16 días con el segundo método. Por experiencia se sabe que la
varianza del primer procedimiento es \(\sigma_{1}^2=12\) y al del
segundo \(\sigma_{2}^2=10\). De las muestras obtenemos que
\(\overline{X}_{1}=136\) para el primer procedimiento y
\(\overline{X}_{2}=128\) para el segundo. Si \(\mu_{1}\) y \(\mu_{2}\)
son los valores esperados para cada uno de los procedimientos, calcular
un intervalo de confianza para \(\mu_{1}-\mu_{2}\) al nivel 99\%.
sol1\{\(\left(5.2989,10.7011\right)\)\}

\hypertarget{soluciuxf3n}{%
\subsubsection{Solución}\label{soluciuxf3n}}

Estamos en el caso de un contraste de comparación de medias de muestras
independientes y en el teórico caso de que las varianzas son conocidas.

Contrastaremos

\[
\left\{
\begin{array}{ll}
H_{0}:\mu_1=\mu_2\\
H_{1}:\mu\not= \mu2 
\end{array}
\right.
\]

El estadístico de contraste es

El \textbf{estadístico de contraste} toma el valor:

\[z_0=\dfrac{\overline{X}_1-\overline{X}_2}{\sqrt{\frac{\sigma_1^2}{n_1}+\frac{\sigma_2^2}{n_2}}}=\frac{136-128}{\sqrt{\frac{3.4641016^2}{25}+\frac{3.1622777^2}{16}}}=7.61.\]

El estadístico sigue, aproximadamente, una distribución normal. La
región crítica del contraste al nivel se significación \(\alpha=0.05\)
es rechazar \(H_0\) si \(z_0<z_{\alpha/2}\) o \(z_0>z_{1\alpha/2}\). Con
nuestros datos

\[z_0=7.61\not< z_{\alpha/2}=z_{0.05}=-1.959964 \mbox{ o } z_0=7.61  \> z_{1-\alpha/2}=1.959964\]
o lo que es lo mismo rechazamos \(H_0\) si
\(|z_0|=7.61> z_{1-\alpha/2}=1.959964\) lo que en este caso es cierto.

Los cuantiles los hemos calculado con

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{alpha=}\FloatTok{0.05}
\KeywordTok{qnorm}\NormalTok{(alpha}\OperatorTok{/}\DecValTok{2}\NormalTok{) }\CommentTok{# o tambien -qnorm(1-alpha/2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -1.959964
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{qnorm}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\NormalTok{alpha}\OperatorTok{/}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.959964
\end{verbatim}

El \(p\)-valor de este contraste para la alternativa bilateral es
\(p\)-valor=\(2\cdot P(Z>|z_0|)\) donde \(Z\) es una normal estándar
\(N(\mu=0,\sigma=1)\). Podemos calcularlo con el código

En nuestro caso

\[2\cdot P(Z>|z_0|)= 2\cdot P(Z>|7.61|)=P(Z>7.61)=2\cdot(1-P(Z\leq 7.61 )),\]

lo podemos calcular con R

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{z0}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 7.61
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{2}\OperatorTok{*}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\KeywordTok{pnorm}\NormalTok{(}\KeywordTok{abs}\NormalTok{(z0)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.00000000000002731149
\end{verbatim}

Es un \(p\)-valor muy pequeño lo que confirma que hay evidencias para
rechazar las hipótesis nula: el rendimiento de los dos métodos de
fabricación no tiene la misma media.

\hypertarget{ejercicio-2}{%
\subsection{Ejercicio 2}\label{ejercicio-2}}

Estamos interesados en comparar la vida media, expresada en horas de dos
tipos de componentes electrónicos. Para ello se toma una muestra de cada
tipo y se obtiene:

\begin{center}
\begin{tabular}{|c|c|c|c|}
\hline Tipo & tamaño & $\overline{x}$ & $\tilde{s}$\\ \hline \hline 1 & 50 & 1260 & 20\\ \hline 2 &
100 & 1240 & 18\\ \hline
\end{tabular}
\end{center}

Calcular un intervalo de confianza para \(\mu_{1}-\mu_{2}\) (\(\mu_{1}\)
esperanza del primer grupo y \(\mu_{2}\) esperanza del segundo grupo) al
nivel 98\% Suponer si es necesario las poblaciones aproximadamente
normales. \% sol1\{\(\left(12.19,27.81\right)\)\}

\hypertarget{soluciuxf3n-1}{%
\subsubsection{Solución}\label{soluciuxf3n-1}}

En este caso tenemos dos muestras independientes de tamaños \(n1=50\),
\(n2=100\) y estadísticos \(\overline{x}_1=1260\),
\(\overline{x}_2=1240\), \(\tilde{s}_1=20\) y \(\tilde{s}_2=18\).

Cargamos los datos en R

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n1=}\DecValTok{50}
\NormalTok{n2=}\DecValTok{120}
\NormalTok{media1=}\DecValTok{1260}
\NormalTok{media2=}\DecValTok{1240}
\NormalTok{desv_tipica1=}\DecValTok{20}
\NormalTok{desv_tipica2=}\DecValTok{18}
\NormalTok{f0=desv_tipica1}\OperatorTok{^}\DecValTok{2}\OperatorTok{/}\NormalTok{desv_tipica2}\OperatorTok{^}\DecValTok{2} \CommentTok{# estadístico de contraste}
\NormalTok{f0}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.234568
\end{verbatim}

Tenemos pues, dos muestras independientes de tamaños muestrales y las
varianzas desconocidas. Haremos un \(t\)-test pero tenemos dos casos:
varianzas desconocidas iguales y varianzas desconocidas distintas.
Primero haremos un test para saber si las varianzas son iguales o
distintas.

El contraste es

\[
\left\{
\begin{array}{ll}
H_{0}:\sigma_1=\sigma_2\\
H_{1}:\sigma_1\not= \sigma_2 
\end{array}
\right.
\]

Se emplea el siguiente \textbf{estadístico de contraste}:

\[
F=\frac{\widetilde{S}_1^2}{\widetilde{S}_2^2}
\] que, si las dos poblaciones son normales y la hipótesis nula
\(H_0:\sigma_1=\sigma_2\) es cierta, tiene distribución \(F\) de Fisher
con grados de libertad \(n_1-1\) y \(n_2-1\).

En nuestro caso
\(f_0=\frac{\tilde{s}_1^2}{\tilde{s}_1^2}= \frac{20^2}{18^2}=1\)

Resolveremos calculando el \(p\)-valor del contraste que este caso es

\[
\begin{array}{l}
\min\{2\cdot P(F_{n_1-1,n_2-1}\leq f_0),2\cdot P(F_{n_1-1,n_2-1}\geq f_0)\}\\=\min\{2\cdot P(F_{50-1,100-1}\leq 1.2345679),2\cdot P(F_{50-1,100-1}\geq 1.2345679)\}
\end{array}
\]

calcularemos el \(p\)-valor con R

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n1=}\DecValTok{50}
\NormalTok{n2=}\DecValTok{100}
\NormalTok{desv_tipica1=}\DecValTok{20}
\NormalTok{desv_tipica2=}\DecValTok{18}
\NormalTok{f0=desv_tipica1}\OperatorTok{^}\DecValTok{2}\OperatorTok{/}\NormalTok{desv_tipica2}\OperatorTok{^}\DecValTok{2} \CommentTok{# estadístico de contraste}
\NormalTok{f0}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.234568
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{2}\OperatorTok{*}\KeywordTok{pf}\NormalTok{(f0,n1}\DecValTok{-1}\NormalTok{,n2}\DecValTok{-1}\NormalTok{,}\DataTypeTok{lower.tail =} \OtherTok{TRUE}\NormalTok{)}\CommentTok{# lower.tail = TRUE es el valor por defecto }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.625115
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{2}\OperatorTok{*}\KeywordTok{pf}\NormalTok{(f0,n1}\DecValTok{-1}\NormalTok{,n2}\DecValTok{-1}\NormalTok{,}\DataTypeTok{lower.tail =} \OtherTok{FALSE}\NormalTok{)}\CommentTok{# o tambien 2*(1-pf(f0,n1-1,n2-1)  }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.3748846
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pvalor=}\KeywordTok{min}\NormalTok{(}\DecValTok{2}\OperatorTok{*}\KeywordTok{pf}\NormalTok{(f0,n1}\DecValTok{-1}\NormalTok{,n2}\DecValTok{-1}\NormalTok{,}\DataTypeTok{lower.tail =} \OtherTok{TRUE}\NormalTok{),}\DecValTok{2}\OperatorTok{*}\KeywordTok{pf}\NormalTok{(f0,n1}\DecValTok{-1}\NormalTok{,n2}\DecValTok{-1}\NormalTok{,}\DataTypeTok{lower.tail =} \OtherTok{FALSE}\NormalTok{))}
\NormalTok{pvalor}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.3748846
\end{verbatim}

El \(p\)-valor es alto así que no podemos rechazar la hipótesis nula;
consideraremos las varianzas iguales.

Así pues vamos a contrastar la igualdad de medias contra que son
distintas:

\[
\left\{
\begin{array}{ll}
H_{0}:\mu_1=\mu_2\\
H_{1}:\mu_2\not= \mu_2 
\end{array}
\right..
\]

El estadístico de contraste sigue una ley \(t\) de Student con
\(n_1+n_2-2\) grados de libertad su fórmula es

\[
T=\frac{\overline{X}_1-\overline{X}_2}
{\sqrt{(\frac1{n_1}+\frac1{n_2})\cdot 
\frac{((n_1-1)\widetilde{S}_1^2+(n_2-1)\widetilde{S}_2^2)}
{(n_1+n_2-2)}}},
\]

en nuestro caso vale

\[
t_0=\frac{1260-1240}
{\sqrt{(\frac1{50}+\frac1{100})\cdot 
\frac{((50-1)\cdot 20^2+(100-1)\cdot  18^2)}
{(n_1+n_2-2)}}}=7.7263624 
\]

con R es

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n1=}\DecValTok{50}
\NormalTok{n2=}\DecValTok{120}
\NormalTok{media1=}\DecValTok{1260}
\NormalTok{media2=}\DecValTok{1240}
\NormalTok{desv_tipica1=}\DecValTok{20}
\NormalTok{desv_tipica2=}\DecValTok{18}
\NormalTok{t0=}\StringTok{ }\NormalTok{(media1}\OperatorTok{-}\NormalTok{media2)}\OperatorTok{/}\NormalTok{(}\KeywordTok{sqrt}\NormalTok{((}\DecValTok{1}\OperatorTok{/}\NormalTok{n1}\OperatorTok{+}\DecValTok{1}\OperatorTok{/}\NormalTok{n2)}\OperatorTok{*}\NormalTok{((n1}\DecValTok{-1}\NormalTok{)}\OperatorTok{*}\NormalTok{desv_tipica1}\OperatorTok{+}\NormalTok{(n2}\DecValTok{-1}\NormalTok{)}\OperatorTok{*}\NormalTok{desv_tipica2}\OperatorTok{^}\DecValTok{2}\NormalTok{)}\OperatorTok{/}\NormalTok{(n1}\OperatorTok{+}\NormalTok{n2}\DecValTok{-2}\NormalTok{)))}
\NormalTok{t0}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 7.745321
\end{verbatim}

el \(p\)-valor para la alternativa bilateral es
\(2\cdot P(t_{N1+n_2-2}>|t_0|)=2\cdot (1-P(t_{N1+n_2-2}>|t_0|)),\) con R
es

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{t0}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 7.745321
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{abs}\NormalTok{(t0)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 7.745321
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 50
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 120
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pvalor=}\StringTok{ }\DecValTok{2}\OperatorTok{*}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\KeywordTok{pt}\NormalTok{(}\KeywordTok{abs}\NormalTok{(t0),}\DataTypeTok{df=}\NormalTok{n1}\OperatorTok{+}\NormalTok{n2}\DecValTok{-2}\NormalTok{))}
\NormalTok{pvalor}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.0000000000008566481
\end{verbatim}

EL \(p\)-valor es extremadamente pequeño hay evidencias en contra de la
hipótesis nula de igualdad de medias contra la hipótesis alternativa de
que son distintas.

El intervalo de confianza al nivel \(1-\alpha=0.95\) es

\[
\left(
\overline{x}_1-\overline{x}_2- t_{n_1+n_2-2,1-\frac{\alpha}{2}}\cdot  \sqrt{\frac{(n_1-1)\cdot \widetilde{S}_1^2+(n_2-1)\cdot\widetilde{S}_2^2}{(n_1+n_2-2)}},
\overline{x}_1-\overline{x}_2+ t_{n_1+n_2-2,1-\frac{\alpha}{2}}\cdot  \sqrt{\frac{(n_1-1)\cdot \widetilde{S}_1^2+(n_2-1)\cdot\widetilde{S}_2^2}
{(n_1+n_2-2)}}
\right)
\]

lo calculamos con R

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n1=}\DecValTok{50}
\NormalTok{n2=}\DecValTok{120}
\NormalTok{media1=}\DecValTok{1260}
\NormalTok{media2=}\DecValTok{1240}
\NormalTok{desv_tipica1=}\DecValTok{20}
\NormalTok{desv_tipica2=}\DecValTok{18}
\NormalTok{alpha=}\FloatTok{0.05}
\KeywordTok{qt}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\NormalTok{alpha}\OperatorTok{/}\DecValTok{2}\NormalTok{,}\DataTypeTok{df=}\NormalTok{n1}\OperatorTok{+}\NormalTok{n2}\DecValTok{-2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.974185
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{IC=}\KeywordTok{c}\NormalTok{(media1}\OperatorTok{-}\NormalTok{media2}\OperatorTok{-}\StringTok{ }\KeywordTok{qt}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\NormalTok{alpha}\OperatorTok{/}\DecValTok{2}\NormalTok{,}\DataTypeTok{df=}\NormalTok{n1}\OperatorTok{+}\NormalTok{n2}\DecValTok{-2}\NormalTok{)}
     \OperatorTok{*}\KeywordTok{sqrt}\NormalTok{((}\DecValTok{1}\OperatorTok{/}\NormalTok{n1}\OperatorTok{+}\DecValTok{1}\OperatorTok{/}\NormalTok{n2)}\OperatorTok{*}\NormalTok{((n1}\DecValTok{-1}\NormalTok{)}\OperatorTok{*}\NormalTok{desv_tipica1}\OperatorTok{+}\NormalTok{(n2}\DecValTok{-1}\NormalTok{)}\OperatorTok{*}\NormalTok{desv_tipica2}\OperatorTok{^}\DecValTok{2}\NormalTok{)}\OperatorTok{/}\NormalTok{(n1}\OperatorTok{+}\NormalTok{n2}\DecValTok{-2}\NormalTok{)),}
\NormalTok{     media1}\OperatorTok{-}\NormalTok{media2}\OperatorTok{+}\StringTok{ }\KeywordTok{qt}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\NormalTok{alpha}\OperatorTok{/}\DecValTok{2}\NormalTok{,}\DataTypeTok{df=}\NormalTok{n1}\OperatorTok{+}\NormalTok{n2}\DecValTok{-2}\NormalTok{)}
     \OperatorTok{*}\KeywordTok{sqrt}\NormalTok{((}\DecValTok{1}\OperatorTok{/}\NormalTok{n1}\OperatorTok{+}\DecValTok{1}\OperatorTok{/}\NormalTok{n2)}\OperatorTok{*}\NormalTok{((n1}\DecValTok{-1}\NormalTok{)}\OperatorTok{*}\NormalTok{desv_tipica1}\OperatorTok{+}\NormalTok{(n2}\DecValTok{-1}\NormalTok{)}\OperatorTok{*}\NormalTok{desv_tipica2}\OperatorTok{^}\DecValTok{2}\NormalTok{)}\OperatorTok{/}\NormalTok{(n1}\OperatorTok{+}\NormalTok{n2}\DecValTok{-2}\NormalTok{)))}
\NormalTok{IC}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 14.90225 25.09775
\end{verbatim}

La diferencia de medias \(\mu_1-\mu_2\) verdadera se encontrará en el
intervalo \((14.902251, 25.097749)\) al nivel de confianza del \(95\%\).
La \(media_1\) es claramente más grande que la dos, en al menos \(14\)

\hypertarget{ejercicio-3}{%
\subsection{Ejercicio 3}\label{ejercicio-3}}

Para reducir la concentración de ácido úrico en la sangre se prueban dos
drogas. La primera se aplica a un grupo de 8 pacientes y la segunda a un
grupo de 10. Las disminuciones observadas en las concentraciones de
ácido úrico de los distintos pacientes expresadas en tantos por cien de
concentración después de aplicado el tratamiento son:

\begin{center}
\begin{tabular}{|c|c|c|c|c|c|c|c|c|c|c|}
droga 1 & 20 & 12 & 16 & 18 & 13 & 22 & 15 & 20\\ \hline droga 2 & 17 & 14 & 12 & 10 & 15 &
13 & 9 & 19 & 20 & 11
\end{tabular}
\end{center}

Calcular un intervalo de confianza para la diferencia de medias entre la
primera droga y la segunda al nivel del 99\%.

Suponer que las reducciones de ácido úrico siguen una distribución
normal son independientes y de igual varianza. Ídem pero suponiendo que
las varianza son distintas.\%sol1\{\(\left(-2.09,8.09\right)\)\}

\hypertarget{ejercicio-4}{%
\subsection{Ejercicio 4}\label{ejercicio-4}}

Para comparar la dureza media de dos tipos de aleaciones (tipo 1 y tipo
2) se hacen 5 pruebas de dureza con la de tipo 1 y 7 con la de tipo 2.
Obteniéndose los resultados siguientes:
\[\overline{X}_{1}=18.2,\quad S_{1}=0.2 \mbox{ y}\]

\[\overline{X}_{2}=17.8;\quad S_{2}=0.5\]

Suponer que la población de las durezas es normal y que las desviaciones
típicas no son iguales. Hacer lo mismo si las varianzas son distintas.
\% , buscar un intervalo de confianza para \(\mu_{1}-\mu_{2}\) con
probabilidad \(0.95\) \% sol1\{\(\left(0.314,0.486\right)\)\}

\hypertarget{ejercicio-5}{%
\subsection{Ejercicio 5}\label{ejercicio-5}}

Se encuestó a dos muestras independientes de internautas, una en Menorca
y otra en Mallorca, sobre si utilizaban telefonía por Internet. La
encuesta de Menorca tuvo un tamaño \(n_1=500\) y \(100\) usuarios
mientras que en Mallorca se encuestaron a \(n_2=750\) y se obtuvo un
resultado de \(138\) usuarios.

\hypertarget{ejercicio-6}{%
\subsection{Ejercicio 6}\label{ejercicio-6}}

Se pregunta a un grupo de 100 personas elegido al azar asiste a un
webinnar sobre tecnología para la banca. Antes de la conferencia se les
pregunta si consideran que Internet es seguna para la banca, después de
la conferencia se les vuelve a preguntar cual es su opinión. Los
resultados fueron los siguientes:

\begin{tabular}{|c|c|cc|}
\cline{3-4}
     \multicolumn{2}{c|}{}& \multicolumn{2}{|c|} {Después}\\\cline{3-4}
   \multicolumn{2}{c|}{} & Sí Segura & No Segura \\\hline
Antes & Sí  Segura &  50 &  30 \\
    & No Segura   &  5 & 15 
\\\hline
\end{tabular}

\hypertarget{soluciuxf3n-2}{%
\subsubsection{Solución}\label{soluciuxf3n-2}}

Es un contraste de comparación de proporciones emparejadas

\hypertarget{ejercicio-7}{%
\subsection{Ejercicio 7}\label{ejercicio-7}}

Tenemos \(10\) ordenadores, deseamos optimizar su funcionamiento. Con
este fin se piensa en ampliar su memoria. Se les pasa una prueba de
rendimiento antes y después de ampliar la memoria. Los resultados
fueron:

\begin{tabular}{|c|llllllllll|}
\hline
 &\multicolumn{10}{|c|}{Ordenador} \\\hline
Muestra\slash Tiempo & 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\\hline
Antes ampliación & 98.70 & 100.48 & 103.75 & 114.41 & 97.82&
91.13 & 85.42 & 96.8 & 107.76 & 112.94\\
\hline
Después ampliación & 99.51 & 114.44 & 108.74 & 97.92 & 103.54&
104.75 & 109.69 & 90.8 & 110.04 & 110.09\\
\hline
\end{tabular}

\hypertarget{soluciuxf3n-3}{%
\subsubsection{Solución}\label{soluciuxf3n-3}}

Es un contraste de medias coon muestras emparejadas

\end{document}
